// Shared diagnostic-code registry (spec 005 "Code registry"). Dependency-free so domain, parser,
// i18n and main can all import it. Each later spec appends its codes here.

export type DiagnosticLayer = 'data' | 'domain' | 'parser' | 'i18n' | 'app';
export type DiagnosticSeverity = 'error' | 'unsupported' | 'warning' | 'unknown' | 'info';

interface CodeDefinition {
  code: string;
  layer: DiagnosticLayer;
  severity: DiagnosticSeverity;
  uRef?: string;
}

export const DIAGNOSTIC_CODE_DEFINITIONS = [
  { code: 'DATA_PACK_MISSING', layer: 'app', severity: 'error' },
  { code: 'DATA_PACK_INTEGRITY_FAILED', layer: 'app', severity: 'error' },
  { code: 'DATA_PACK_NOT_VALIDATED', layer: 'app', severity: 'error' },
  { code: 'DATA_PACK_SCHEMA_UNSUPPORTED', layer: 'app', severity: 'error' },
  { code: 'DATA_CONFLICT', layer: 'domain', severity: 'unknown' },
  { code: 'GAME_TERM_FALLBACK_EN', layer: 'i18n', severity: 'info' },
  { code: 'GAME_TERM_MISSING', layer: 'i18n', severity: 'warning' },
  { code: 'NOT_A_POE2_ITEM', layer: 'parser', severity: 'error' },
  { code: 'UNSUPPORTED_CLIPBOARD_LOCALE', layer: 'parser', severity: 'error' },
  { code: 'BASE_TYPE_UNRESOLVED', layer: 'parser', severity: 'error' },
  { code: 'ITEM_CLASS_UNRESOLVED', layer: 'parser', severity: 'error' },
  { code: 'ITEM_LEVEL_MISSING', layer: 'parser', severity: 'error' },
  { code: 'AFFIX_UNRESOLVED', layer: 'parser', severity: 'warning' },
  { code: 'AFFIX_AMBIGUOUS', layer: 'parser', severity: 'info' },
  { code: 'AFFIX_SIDE_UNKNOWN', layer: 'parser', severity: 'warning' },
  { code: 'MARKER_UNCONFIRMED', layer: 'parser', severity: 'info' },
  { code: 'DESECRATED_STATE_UNDETERMINED', layer: 'parser', severity: 'warning' },
  { code: 'MARK_UNRESOLVED', layer: 'parser', severity: 'warning' },
  { code: 'SPECIAL_ITEM_DETECTED', layer: 'parser', severity: 'info' },
  { code: 'TIME_LOST_JEWEL_DETECTED', layer: 'parser', severity: 'info' },
  { code: 'NORMAL_COPY_LIMITED_DETAIL', layer: 'parser', severity: 'info' },
  { code: 'UNKNOWN_CURRENCY', layer: 'domain', severity: 'unknown' },
  { code: 'UNKNOWN_OMEN', layer: 'domain', severity: 'unknown' },
  { code: 'PARSER_INSUFFICIENT', layer: 'domain', severity: 'unknown' },
  { code: 'ITEM_NOT_RARE', layer: 'domain', severity: 'error' },
  { code: 'ITEM_CORRUPTED', layer: 'domain', severity: 'error' },
  { code: 'ITEM_ALREADY_DESECRATED', layer: 'domain', severity: 'error' },
  { code: 'EXISTING_DESECRATION_UNDETERMINED', layer: 'domain', severity: 'unknown', uRef: 'U-014' },
  { code: 'ITEM_STATE_UNDOCUMENTED', layer: 'domain', severity: 'unknown', uRef: 'U-015' },
  { code: 'BONE_INCOMPATIBLE_ITEM_CLASS', layer: 'domain', severity: 'error' },
  { code: 'ITEM_CLASS_TARGET_UNMAPPED', layer: 'domain', severity: 'unknown' },
  { code: 'GNAWED_ITEM_LEVEL_TOO_HIGH', layer: 'domain', severity: 'error' },
  { code: 'LICH_OMEN_INCOMPATIBLE_WITH_BONE', layer: 'domain', severity: 'error' },
  { code: 'OMEN_INCOMPATIBLE_WITH_BONE', layer: 'domain', severity: 'error' },
  { code: 'ALTERED_COLLARBONE_LICH_OMEN_CONFLICT', layer: 'domain', severity: 'error' },
  { code: 'CONFLICTING_SIDE_OMENS', layer: 'domain', severity: 'unsupported' },
  { code: 'UNKNOWN_MULTIPLE_LICH_OMENS', layer: 'domain', severity: 'unknown' },
  { code: 'UNKNOWN_PUTREFACTION_OMEN_COMBINATION', layer: 'domain', severity: 'unknown' },
  { code: 'UNKNOWN_PUTREFACTION_MARK_INTERACTION', layer: 'domain', severity: 'unknown' },
  { code: 'UNKNOWN_ALTERED_PUTREFACTION_INTERACTION', layer: 'domain', severity: 'unknown', uRef: 'U-002' },
  { code: 'UNSUPPORTED_SPECIAL_ITEM', layer: 'domain', severity: 'unsupported', uRef: 'U-005' },
  { code: 'SPECIAL_JEWEL_RULE', layer: 'domain', severity: 'unsupported', uRef: 'U-006' },
  { code: 'RULE_EVIDENCE_MISSING', layer: 'domain', severity: 'unknown' },
  { code: 'AFFIX_LIMIT_UNKNOWN', layer: 'domain', severity: 'unknown' },
  { code: 'AFFIX_CAPACITY_UNDETERMINED', layer: 'domain', severity: 'unknown' },
  { code: 'MARK_STATE_UNDETERMINED', layer: 'domain', severity: 'unknown' },
  { code: 'FRACTURED_STATE_UNDETERMINED', layer: 'domain', severity: 'unknown', uRef: 'U-011' },
  { code: 'LEGACY_CURRENCY', layer: 'domain', severity: 'info' },
  { code: 'PARSER_PARTIAL_MOD_GROUPS', layer: 'domain', severity: 'warning' },
  { code: 'UNKNOWN_MARK_SIDE_INTERACTION', layer: 'domain', severity: 'unknown', uRef: 'U-001' },
  { code: 'UNKNOWN_FRACTURED_MARK_INTERACTION', layer: 'domain', severity: 'unknown', uRef: 'U-007' },
  { code: 'NO_REMOVABLE_AFFIX_ON_SIDE', layer: 'domain', severity: 'unsupported', uRef: 'U-007' },
  { code: 'UNKNOWN_MIXED_CAPACITY_SIDE_CHOICE', layer: 'domain', severity: 'unknown', uRef: 'U-012' },
  { code: 'UNKNOWN_ANCIENT_MARK_FLOOR', layer: 'domain', severity: 'unknown', uRef: 'U-008' },
  { code: 'MARK_REPLACED_FIRST', layer: 'domain', severity: 'info' },
  { code: 'CONDITIONAL_TAGS_INCOMPLETE', layer: 'domain', severity: 'warning' },
  { code: 'FORCED_LICH_POOL_EMPTY', layer: 'domain', severity: 'warning' },
  { code: 'ANCIENT_BENEFIT_OVERRIDDEN_BY_LICH_OMEN', layer: 'domain', severity: 'warning' },
  { code: 'MARK_FLOOR_OVERRIDDEN_BY_LICH_OMEN', layer: 'domain', severity: 'info' },
  { code: 'UNKNOWN_LICH_FALLBACK_COMPOSITION', layer: 'domain', severity: 'unknown', uRef: 'U-013' },
  { code: 'FAMILY_FLOOR_FALLBACK_TIER', layer: 'domain', severity: 'info' },
  { code: 'EXCLUSIVE_OPTION_GUARANTEE_NOTE', layer: 'domain', severity: 'info' },
  { code: 'ECHOES_REROLL_AVAILABLE', layer: 'domain', severity: 'info' },
  { code: 'ITEM_WILL_BE_CORRUPTED', layer: 'domain', severity: 'warning' },
  { code: 'ANCIENT_FLOOR_NOT_GUARANTEED_PUTREFACTION', layer: 'domain', severity: 'warning' },
  { code: 'PUTREFACTION_SLOT_COUNT_WORKING_MODEL', layer: 'domain', severity: 'info', uRef: 'U-007' },
  { code: 'WRONG_SIDE', layer: 'domain', severity: 'info' },
  { code: 'ITEM_LEVEL_TOO_LOW', layer: 'domain', severity: 'info' },
  { code: 'BELOW_MINIMUM_MODIFIER_LEVEL', layer: 'domain', severity: 'info' },
  { code: 'MOD_GROUP_CONFLICT', layer: 'domain', severity: 'info' },
  { code: 'BASE_TAG_NOT_ELIGIBLE', layer: 'domain', severity: 'info' },
  { code: 'SOURCE_NOT_ENABLED', layer: 'domain', severity: 'info' },
  { code: 'LICH_SOURCE_NOT_SELECTED', layer: 'domain', severity: 'info' },
  { code: 'OTHER_LICH_BLOCKED_BY_FORCE_OMEN', layer: 'domain', severity: 'info' },
  { code: 'LICH_CLASSIFICATION_UNDER_REVIEW', layer: 'domain', severity: 'info' },
  { code: 'PUTREFACTION_EXCLUDES_EXCLUSIVE', layer: 'domain', severity: 'info' },
  { code: 'POSSIBLY_BLOCKED_BY_UNRESOLVED_AFFIX', layer: 'domain', severity: 'info' },
  { code: 'BASE_POOL_ONLY', layer: 'domain', severity: 'info' },
] as const satisfies readonly CodeDefinition[];

export type DiagnosticCode = (typeof DIAGNOSTIC_CODE_DEFINITIONS)[number]['code'];
export const DIAGNOSTIC_CODES: readonly DiagnosticCode[] = DIAGNOSTIC_CODE_DEFINITIONS.map((d) => d.code);
