// U-009 data discovery (SoT §20): records observed RePoE facts that the adapter's source
// classification relies on. Output is deterministic for a given snapshot.
import { readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

interface RawSpawnWeight { tag: string; weight: number }
interface RawMod {
  domain: string;
  generation_type: string;
  name: string;
  implicit_tags: string[];
  spawn_weights: RawSpawnWeight[];
}
interface RawBase { domain?: string; item_class: string; release_state: string }
interface SnapshotRecord { observedVersion: string; files: Array<{ id: string; path: string; sha256: string }> }

const snapshotDir = process.argv[2];
if (!snapshotDir) throw new Error('usage: tsx scripts/inspect-snapshot.ts <snapshot dir>');

const readJson = <T>(path: string): T => JSON.parse(readFileSync(join(snapshotDir, path), 'utf8')) as T;
const snapshot = readJson<SnapshotRecord>('snapshot.json');
const fileRef = (path: string): string => {
  const file = snapshot.files.find((f) => f.path === path);
  if (!file) throw new Error(`${path} missing from snapshot.json`);
  return file.id;
};

const mods = readJson<Record<string, RawMod>>('mods.min.json');
const bases = readJson<Record<string, RawBase>>('base_items.min.json');

const tally = (values: Iterable<string>): Record<string, number> => {
  const out: Record<string, number> = {};
  for (const v of values) out[v] = (out[v] ?? 0) + 1;
  return Object.fromEntries(Object.entries(out).sort(([a], [b]) => a.localeCompare(b)));
};

const affixMods = Object.values(mods).filter((m) => m.generation_type === 'prefix' || m.generation_type === 'suffix');
const desecrated = affixMods.filter((m) => m.domain === 'desecrated');
const positiveTags = (m: RawMod): string[] => m.spawn_weights.filter((w) => w.weight > 0).map((w) => w.tag);

const releasedBaseDomainsByClass: Record<string, Record<string, number>> = {};
for (const base of Object.values(bases)) {
  if (base.release_state !== 'released' || base.domain === undefined) continue;
  const byDomain = (releasedBaseDomainsByClass[base.item_class] ??= {});
  byDomain[base.domain] = (byDomain[base.domain] ?? 0) + 1;
}

const output = {
  $comment: 'Generated by scripts/inspect-snapshot.ts (U-009). Do not edit observed facts by hand.',
  snapshot: { observedVersion: snapshot.observedVersion, modsRef: fileRef('mods.min.json'), baseItemsRef: fileRef('base_items.min.json') },
  observed: {
    prefixSuffixModsByDomain: tally(affixMods.map((m) => m.domain)),
    desecratedByGenerationType: tally(desecrated.map((m) => m.generation_type)),
    desecratedPositiveSpawnTags: tally(desecrated.flatMap(positiveTags)),
    desecratedImplicitTags: tally(desecrated.flatMap((m) => m.implicit_tags)),
    releasedBaseDomainsByItemClass: Object.fromEntries(
      Object.entries(releasedBaseDomainsByClass).sort(([a], [b]) => a.localeCompare(b)),
    ),
  },
  mapping: {
    regular: 'mod.domain === base.domain (ordinary item domain of the evaluated base; RePoE mods_by_base semantics, SoT §6.2, §7.4)',
    desecratedExclusive: "mod.domain === 'desecrated' && generation_type in {prefix, suffix} (SoT §7.4)",
    lichValidationTags: { amanamu: 'amanamu_mod', ulaman: 'ulaman_mod', kurgal: 'kurgal_mod' },
    otherworldlyGateTag: 'breach_desecration',
    evidenceLevel: 'VERIFIED_PRIMARY',
  },
};

const target = join('data-source', 'rules', 'source-classification.json');
writeFileSync(target, `${JSON.stringify(output, null, 2)}\n`);
console.log(`Wrote ${target}`);
